"""
Approval Workflow for Personal AI Employee - Silver Tier

Human-in-the-Loop (HITL) approval system for sensitive actions.
Manages approval requests, tracks approvals, and enforces approval policies.
"""

import logging
import re
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Tuple, Any

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# Approval request template
APPROVAL_REQUEST_TEMPLATE = """---
type: approval_request
action: {action_type}
created: {created}
expires: {expires}
status: pending
priority: {priority}
request_id: {request_id}
---

# Approval Request: {action_title}

## Action Details

{action_details}

## Reason for Approval

{approval_reason}

## Risk Assessment

- **Financial Impact**: {financial_impact}
- **Reputation Risk**: {reputation_risk}
- **Time Sensitivity**: {time_sensitivity}

## Recommended Action

{recommended_action}

## Instructions

**To Approve:** Move this file to `/Approved` folder

**To Reject:** Move this file to `/Rejected` folder with reason added below

**To Request Changes:** Add comments below and move back to `Pending_Approval`

---

## Approval History

- **Created:** {created}
- **Expires:** {expires}
- **Request ID:** {request_id}

---
*Generated by AI Employee Approval Workflow*
"""


class ApprovalWorkflow:
    """
    Human-in-the-Loop approval workflow manager.
    
    Usage:
        workflow = ApprovalWorkflow(vault_path)
        
        # Check if action requires approval
        requires_approval, reason = workflow.requires_approval(task_metadata)
        
        # Create approval request
        request_path = workflow.create_approval_request(action_details)
        
        # Process approved actions
        approved = workflow.get_approved_actions()
    """
    
    # Approval thresholds (from Company Handbook)
    AUTO_APPROVE_UNDER = 50  # Dollars
    REQUIRE_APPROVAL_OVER = 50
    REQUIRE_HUMAN_OVER = 200
    
    # Approval expiration (hours)
    APPROVAL_EXPIRY_HOURS = 24
    
    def __init__(self, vault_path: Path):
        """
        Initialize the approval workflow.
        
        Args:
            vault_path: Path to the Obsidian vault
        """
        self.vault_path = Path(vault_path)
        
        # Folder paths
        self.pending_path = self.vault_path / "Pending_Approval"
        self.approved_path = self.vault_path / "Approved"
        self.rejected_path = self.vault_path / "Rejected"
        self.done_path = self.vault_path / "Done"
        
        # Ensure folders exist
        for path in [self.pending_path, self.approved_path, 
                     self.rejected_path, self.done_path]:
            path.mkdir(exist_ok=True)
        
        # Approval request counter
        self.request_counter = self._load_request_counter()
        
        logger.info(f"ApprovalWorkflow initialized at {vault_path}")
    
    def _load_request_counter(self) -> int:
        """Load the approval request counter"""
        counter_file = self.vault_path / "Logs" / "approval_counter.txt"
        if counter_file.exists():
            try:
                return int(counter_file.read_text().strip())
            except:
                pass
        return 0
    
    def _save_request_counter(self, counter: int):
        """Save the approval request counter"""
        counter_file = self.vault_path / "Logs" / "approval_counter.txt"
        counter_file.parent.mkdir(exist_ok=True)
        counter_file.write_text(str(counter))
    
    def _generate_request_id(self) -> str:
        """Generate a unique approval request ID"""
        self.request_counter += 1
        self._save_request_counter(self.request_counter)
        
        timestamp = datetime.now().strftime('%Y%m%d')
        return f"APR_{timestamp}_{self.request_counter:04d}"
    
    def requires_approval(
        self, 
        task_file: Path = None,
        task_metadata: dict = None
    ) -> Tuple[bool, str]:
        """
        Determine if an action requires human approval.
        
        Args:
            task_file: Path to task file (alternative to metadata)
            task_metadata: Task metadata dictionary
            
        Returns:
            Tuple of (requires_approval: bool, reason: str)
        """
        # Parse task file if provided
        if task_file:
            task_metadata = self._parse_task_file(task_file)
        
        if not task_metadata:
            return True, "Unable to parse task - manual review required"
        
        action_type = task_metadata.get('type', 'unknown')
        
        # Check action type specific rules
        if action_type == 'payment':
            return self._check_payment_approval(task_metadata)
        
        elif action_type == 'email':
            return self._check_email_approval(task_metadata)
        
        elif action_type in ['linkedin', 'social_post']:
            return self._check_social_approval(task_metadata)
        
        elif action_type == 'invoice':
            return self._check_invoice_approval(task_metadata)
        
        # Check priority-based approval
        priority = task_metadata.get('priority', 'medium')
        if priority == 'critical':
            return True, "Critical priority actions require human approval"
        
        # Default: no approval required for routine tasks
        return False, "Auto-execution allowed"
    
    def _check_payment_approval(self, metadata: dict) -> Tuple[bool, str]:
        """Check if payment requires approval"""
        amount = float(metadata.get('amount', 0))
        is_recurring = metadata.get('is_recurring', False)
        
        if amount > self.REQUIRE_HUMAN_OVER:
            return True, f"Payment ${amount:.2f} exceeds human approval threshold (${self.REQUIRE_HUMAN_OVER})"
        
        if amount > self.REQUIRE_APPROVAL_OVER:
            return True, f"Payment ${amount:.2f} exceeds auto-approve threshold (${self.REQUIRE_APPROVAL_OVER})"
        
        if is_recurring and amount <= self.AUTO_APPROVE_UNDER:
            return False, f"Recurring payment under ${self.AUTO_APPROVE_UNDER} - auto-approve"
        
        if amount <= self.AUTO_APPROVE_UNDER:
            return False, f"Payment under ${self.AUTO_APPROVE_UNDER} - auto-approve"
        
        return True, "Payment requires approval per Company Handbook"
    
    def _check_email_approval(self, metadata: dict) -> Tuple[bool, str]:
        """Check if email action requires approval"""
        # Check if sending to unknown recipient
        is_known_sender = metadata.get('is_known_sender', True)
        is_outbound = metadata.get('is_outbound', False)
        
        if is_outbound and not is_known_sender:
            return True, "Email to unknown recipient requires approval"
        
        # Check for sensitive content
        content = metadata.get('content', '')
        sensitive_keywords = ['confidential', 'contract', 'legal', 'financial']
        
        if any(kw in content.lower() for kw in sensitive_keywords):
            return True, "Email contains sensitive content requiring approval"
        
        return False, "Email can be sent without approval"
    
    def _check_social_approval(self, metadata: dict) -> Tuple[bool, str]:
        """Check if social media post requires approval"""
        # All social posts require approval by default
        return True, "Social media posts require human approval before publishing"
    
    def _check_invoice_approval(self, metadata: dict) -> Tuple[bool, str]:
        """Check if invoice action requires approval"""
        amount = float(metadata.get('amount', 0))
        
        # All invoices over threshold require approval
        if amount > self.REQUIRE_APPROVAL_OVER:
            return True, f"Invoice ${amount:.2f} exceeds approval threshold"
        
        return False, "Invoice can be sent without approval"
    
    def create_approval_request(
        self,
        action_type: str,
        action_details: dict,
        priority: str = 'medium',
        task_file: Path = None
    ) -> Path:
        """
        Create an approval request file.
        
        Args:
            action_type: Type of action (payment, email, social_post, etc.)
            action_details: Dictionary with action-specific details
            priority: Priority level
            task_file: Optional reference to original task file
            
        Returns:
            Path to created approval request file
        """
        request_id = self._generate_request_id()
        created = datetime.now()
        expires = created + timedelta(hours=self.APPROVAL_EXPIRY_HOURS)
        
        # Generate action title
        action_title = self._generate_action_title(action_type, action_details)
        
        # Format action details
        details_text = self._format_action_details(action_type, action_details)
        
        # Determine approval reason
        approval_reason = self._determine_approval_reason(action_type, action_details)
        
        # Assess risks
        financial_impact = self._assess_financial_impact(action_type, action_details)
        reputation_risk = self._assess_reputation_risk(action_type, action_details)
        time_sensitivity = self._assess_time_sensitivity(priority, action_details)
        
        # Recommended action
        recommended_action = self._get_recommended_action(action_type, action_details)
        
        # Generate content
        content = APPROVAL_REQUEST_TEMPLATE.format(
            action_type=action_type,
            created=created.strftime('%Y-%m-%d %H:%M:%S'),
            expires=expires.strftime('%Y-%m-%d %H:%M:%S'),
            status='pending',
            priority=priority,
            request_id=request_id,
            action_title=action_title,
            action_details=details_text,
            approval_reason=approval_reason,
            financial_impact=financial_impact,
            reputation_risk=reputation_risk,
            time_sensitivity=time_sensitivity,
            recommended_action=recommended_action
        )
        
        # Create filename
        filename = f"{request_id}_{action_type}_{created.strftime('%Y%m%d_%H%M%S')}.md"
        filepath = self.pending_path / filename
        
        # Write file
        filepath.write_text(content, encoding='utf-8')
        
        logger.info(f"Created approval request: {filepath}")
        
        # Store request metadata
        self._store_request_metadata(request_id, {
            'action_type': action_type,
            'action_details': action_details,
            'priority': priority,
            'created': created.isoformat(),
            'expires': expires.isoformat(),
            'task_file': str(task_file) if task_file else None
        })
        
        return filepath
    
    def _generate_action_title(
        self, 
        action_type: str, 
        action_details: dict
    ) -> str:
        """Generate a human-readable action title"""
        titles = {
            'payment': f"Payment of ${action_details.get('amount', 0):.2f} to {action_details.get('recipient', 'Unknown')}",
            'email': f"Send email to {action_details.get('recipient', 'Unknown')}",
            'social_post': f"Post to {action_details.get('platform', 'social media')}",
            'linkedin': f"Post to LinkedIn: {action_details.get('topic', 'Business Update')}",
            'invoice': f"Send invoice for ${action_details.get('amount', 0):.2f}",
        }
        
        return titles.get(action_type, f"Action: {action_type}")
    
    def _format_action_details(
        self, 
        action_type: str, 
        details: dict
    ) -> str:
        """Format action details for display"""
        formatted = []
        
        if action_type == 'payment':
            formatted.append(f"- **Amount:** ${details.get('amount', 0):.2f}")
            formatted.append(f"- **Recipient:** {details.get('recipient', 'Unknown')}")
            formatted.append(f"- **Reason:** {details.get('reason', 'Not specified')}")
            formatted.append(f"- **Recurring:** {details.get('is_recurring', False)}")
        
        elif action_type == 'email':
            formatted.append(f"- **To:** {details.get('to', 'Unknown')}")
            formatted.append(f"- **Subject:** {details.get('subject', 'No subject')}")
            formatted.append(f"- **Preview:** {details.get('body', '')[:200]}...")
        
        elif action_type in ['social_post', 'linkedin']:
            formatted.append(f"- **Platform:** {details.get('platform', action_type)}")
            formatted.append(f"- **Content:** {details.get('content', '')[:200]}...")
            formatted.append(f"- **Schedule:** {details.get('schedule_time', 'Immediate')}")
        
        elif action_type == 'invoice':
            formatted.append(f"- **Client:** {details.get('client', 'Unknown')}")
            formatted.append(f"- **Amount:** ${details.get('amount', 0):.2f}")
            formatted.append(f"- **Service:** {details.get('service', 'Not specified')}")
        
        else:
            for key, value in details.items():
                formatted.append(f"- **{key}:** {value}")
        
        return '\n'.join(formatted) if formatted else "No additional details"
    
    def _determine_approval_reason(
        self, 
        action_type: str, 
        details: dict
    ) -> str:
        """Determine why this action requires approval"""
        reasons = {
            'payment': self._get_payment_approval_reason(details),
            'email': "Outbound communication requires review for quality and accuracy",
            'social_post': "Public-facing content requires human review",
            'linkedin': "Professional social media posts require approval",
            'invoice': "Client-facing financial document requires review",
        }
        
        return reasons.get(action_type, "Company policy requires approval for this action type")
    
    def _get_payment_approval_reason(self, details: dict) -> str:
        """Get specific reason for payment approval"""
        amount = float(details.get('amount', 0))
        
        if amount > self.REQUIRE_HUMAN_OVER:
            return f"Payment amount (${amount:.2f}) exceeds human approval threshold (${self.REQUIRE_HUMAN_OVER})"
        
        if amount > self.REQUIRE_APPROVAL_OVER:
            return f"Payment amount (${amount:.2f}) exceeds auto-approve threshold (${self.REQUIRE_APPROVAL_OVER})"
        
        return "Payment requires approval per Company Handbook guidelines"
    
    def _assess_financial_impact(
        self, 
        action_type: str, 
        details: dict
    ) -> str:
        """Assess financial impact of the action"""
        if action_type == 'payment':
            amount = float(details.get('amount', 0))
            if amount > 200:
                return "High - Significant financial outflow"
            elif amount > 50:
                return "Medium - Moderate financial impact"
            else:
                return "Low - Minimal financial impact"
        
        elif action_type == 'invoice':
            amount = float(details.get('amount', 0))
            if amount > 500:
                return "High - Significant revenue"
            elif amount > 100:
                return "Medium - Moderate revenue"
            else:
                return "Low - Small transaction"
        
        return "Low - No direct financial impact"
    
    def _assess_reputation_risk(
        self, 
        action_type: str, 
        details: dict
    ) -> str:
        """Assess reputation risk of the action"""
        if action_type in ['email', 'social_post', 'linkedin']:
            return "Medium - Public/client-facing communication"
        
        if action_type == 'payment':
            recipient = details.get('recipient', '')
            if 'vendor' in recipient.lower() or 'supplier' in recipient.lower():
                return "Low - Routine vendor payment"
            return "Medium - Payment to new recipient"
        
        return "Low - Internal action"
    
    def _assess_time_sensitivity(
        self, 
        priority: str, 
        details: dict
    ) -> str:
        """Assess time sensitivity of the action"""
        priority_map = {
            'critical': "High - Requires immediate attention",
            'high': "Medium-High - Should be addressed within 1 hour",
            'medium': "Medium - Should be addressed within 4 hours",
            'low': "Low - Can wait up to 24 hours"
        }
        
        return priority_map.get(priority, "Medium - Standard processing time")
    
    def _get_recommended_action(
        self, 
        action_type: str, 
        details: dict
    ) -> str:
        """Get recommended action for the approver"""
        recommendations = {
            'payment': "Verify recipient details and amount. Approve if legitimate business expense.",
            'email': "Review content for accuracy and tone. Approve if appropriate for recipient.",
            'social_post': "Review content for brand alignment. Approve if consistent with company voice.",
            'linkedin': "Review for professional tone and value. Approve if adds value to network.",
            'invoice': "Verify client, amount, and service details. Approve if accurate.",
        }
        
        return recommendations.get(action_type, "Review details and use best judgment")
    
    def _store_request_metadata(self, request_id: str, metadata: dict):
        """Store approval request metadata for tracking"""
        metadata_file = self.vault_path / "Logs" / "approval_requests.jsonl"
        metadata_file.parent.mkdir(exist_ok=True)
        
        import json
        record = {
            'request_id': request_id,
            'timestamp': datetime.now().isoformat(),
            **metadata
        }
        
        with open(metadata_file, 'a', encoding='utf-8') as f:
            f.write(json.dumps(record) + '\n')
    
    def _parse_task_file(self, task_file: Path) -> dict:
        """Parse task file to extract metadata"""
        try:
            content = task_file.read_text(encoding='utf-8')
            metadata = {}
            
            # Parse frontmatter
            match = re.match(r'^---\s*\n(.*?)\n---\s*\n', content, re.DOTALL)
            
            if match:
                yaml_content = match.group(1)
                
                for line in yaml_content.split('\n'):
                    if ':' in line:
                        key, value = line.split(':', 1)
                        key = key.strip()
                        value = value.strip()
                        
                        # Remove quotes
                        if (value.startswith('"') and value.endswith('"')) or \
                           (value.startswith("'") and value.endswith("'")):
                            value = value[1:-1]
                        
                        # Type conversion
                        if value.lower() == 'true':
                            value = True
                        elif value.lower() == 'false':
                            value = False
                        else:
                            try:
                                value = float(value)
                                if value == int(value):
                                    value = int(value)
                            except ValueError:
                                pass
                        
                        metadata[key] = value
            
            # Add content
            metadata['content'] = content
            
            return metadata
            
        except Exception as e:
            logger.error(f"Error parsing task file {task_file}: {e}")
            return {}
    
    def get_pending_approvals(self) -> List[Path]:
        """Get list of pending approval requests"""
        return list(self.pending_path.glob("*.md"))
    
    def get_approved_actions(self) -> List[Path]:
        """Get list of approved actions ready for execution"""
        return list(self.approved_path.glob("*.md"))
    
    def get_rejected_actions(self) -> List[Path]:
        """Get list of rejected actions"""
        return list(self.rejected_path.glob("*.md"))
    
    def process_approval(
        self, 
        request_file: Path, 
        approved: bool,
        reason: str = None
    ) -> bool:
        """
        Process an approval decision.
        
        Args:
            request_file: Path to approval request file
            approved: Whether the action was approved
            reason: Optional reason for rejection
            
        Returns:
            True if processing succeeded
        """
        try:
            if approved:
                # Move to Approved folder
                dest = self.approved_path / request_file.name
                request_file.rename(dest)
                logger.info(f"Approval request approved: {dest}")
            else:
                # Add rejection reason and move to Rejected
                content = request_file.read_text(encoding='utf-8')
                content += f"\n\n## Rejection Reason\n\n{reason or 'Not specified'}\n"
                
                dest = self.rejected_path / request_file.name
                dest.write_text(content, encoding='utf-8')
                request_file.unlink()
                logger.info(f"Approval request rejected: {dest}")
            
            return True
            
        except Exception as e:
            logger.error(f"Error processing approval: {e}")
            return False
    
    def check_expired_approvals(self) -> List[Path]:
        """
        Check for expired approval requests.
        
        Returns:
            List of expired approval request files
        """
        expired = []
        now = datetime.now()
        
        for request_file in self.pending_path.glob("*.md"):
            try:
                content = request_file.read_text(encoding='utf-8')
                
                # Parse expires date from frontmatter
                match = re.search(r'expires:\s*(\d{4}-\d{2}-\d{2}[^:\n]*)', content)
                if match:
                    expires_str = match.group(1)
                    try:
                        expires = datetime.fromisoformat(expires_str)
                        if now > expires:
                            expired.append(request_file)
                    except:
                        pass
                        
            except Exception as e:
                logger.warning(f"Error checking expiry for {request_file}: {e}")
        
        return expired
    
    def get_approval_statistics(self) -> dict:
        """Get approval workflow statistics"""
        pending = self.get_pending_approvals()
        approved = self.get_approved_actions()
        rejected = self.get_rejected_actions()
        expired = self.check_expired_approvals()
        
        return {
            'pending_count': len(pending),
            'approved_count': len(approved),
            'rejected_count': len(rejected),
            'expired_count': len(expired),
            'pending_files': [f.name for f in pending[:5]],  # First 5
            'approved_files': [f.name for f in approved[:5]]
        }
