"""
Plan Generator for Personal AI Employee - Silver Tier

Generates structured Plan.md files using Claude Code reasoning.
Plans include task breakdown, action items, and progress tracking.
"""

import logging
import re
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional, Any

from .memory_store import MemoryStore

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# Plan template
PLAN_TEMPLATE = """---
type: plan
task_id: {task_id}
task_file: {task_file}
created: {created}
status: {status}
priority: {priority}
estimated_steps: {estimated_steps}
---

# Plan: {task_title}

## Task Summary
{task_summary}

## Context
{context}

## Action Plan

{action_plan}

## Required Resources
{resources}

## Potential Blockers
{blockers}

## Success Criteria
{success_criteria}

## Progress Tracking

- [ ] Step 1: {step_1}
- [ ] Step 2: {step_2}
- [ ] Step 3: {step_3}
{additional_steps}

## Notes

{notes}

---
*Generated by AI Employee Plan Generator at {created}*
"""


class PlanGenerator:
    """
    Generates structured Plan.md files for tasks.
    
    Usage:
        generator = PlanGenerator(vault_path)
        
        # Generate plan for a task
        plan_path = generator.create_plan(task_file)
        
        # Generate plan with custom context
        plan_path = generator.create_plan(task_file, context)
    """
    
    def __init__(self, vault_path: Path):
        """
        Initialize the plan generator.
        
        Args:
            vault_path: Path to the Obsidian vault
        """
        self.vault_path = Path(vault_path)
        self.plans_path = self.vault_path / "Plans"
        self.plans_path.mkdir(exist_ok=True)
        
        # Initialize memory store for context
        self.memory_store = MemoryStore(vault_path)
        
        logger.info(f"PlanGenerator initialized at {vault_path}")
    
    def create_plan(
        self, 
        task_file: Path, 
        context: dict = None
    ) -> Path:
        """
        Create a Plan.md file for a task.
        
        Args:
            task_file: Path to the task file
            context: Optional additional context
            
        Returns:
            Path to created plan file
        """
        try:
            # Read task content
            task_content = task_file.read_text(encoding='utf-8')
            frontmatter = self._parse_frontmatter(task_content)
            
            # Get memory context
            memory_context = self._get_memory_context(frontmatter, task_content)
            
            # Merge with provided context
            if context:
                memory_context.update(context)
            
            # Generate plan content
            plan_content = self._generate_plan_content(
                task_file=task_file,
                task_content=task_content,
                frontmatter=frontmatter,
                context=memory_context
            )
            
            # Create plan file
            plan_filename = self._generate_plan_filename(task_file, frontmatter)
            plan_path = self.plans_path / plan_filename
            
            plan_path.write_text(plan_content, encoding='utf-8')
            
            logger.info(f"Created plan: {plan_path}")
            return plan_path
            
        except Exception as e:
            logger.error(f"Failed to create plan for {task_file}: {e}")
            raise
    
    def _generate_plan_content(
        self,
        task_file: Path,
        task_content: str,
        frontmatter: dict,
        context: dict
    ) -> str:
        """
        Generate the full plan content.
        
        Args:
            task_file: Path to task file
            task_content: Full task content
            frontmatter: Parsed frontmatter
            context: Context dictionary
            
        Returns:
            Formatted plan content
        """
        # Extract task information
        task_id = task_file.stem
        task_title = frontmatter.get('subject', frontmatter.get('type', 'Unknown Task'))
        task_type = frontmatter.get('type', 'unknown')
        priority = frontmatter.get('priority', 'medium')
        created = datetime.now().isoformat()
        
        # Generate task summary
        task_summary = self._generate_task_summary(task_content, frontmatter)
        
        # Format context
        context_text = self._format_context(context)
        
        # Generate action plan
        action_plan = self._generate_action_plan(task_type, frontmatter, context)
        
        # Identify resources
        resources = self._identify_resources(task_type, frontmatter)
        
        # Identify potential blockers
        blockers = self._identify_blockers(task_type, frontmatter, context)
        
        # Define success criteria
        success_criteria = self._define_success_criteria(task_type, frontmatter)
        
        # Generate action steps
        steps = self._generate_action_steps(task_type, frontmatter)
        
        # Generate notes
        notes = self._generate_notes(task_type, context)
        
        # Format additional steps
        additional_steps = ""
        for i, step in enumerate(steps[3:], 4):
            additional_steps += f"- [ ] Step {i}: {step}\n"
        
        if not additional_steps:
            additional_steps = "- [ ] Additional steps as needed\n"
        
        # Fill template
        plan_content = PLAN_TEMPLATE.format(
            task_id=task_id,
            task_file=str(task_file),
            created=created,
            status='pending',
            priority=priority,
            estimated_steps=len(steps),
            task_title=task_title,
            task_summary=task_summary,
            context=context_text,
            action_plan=action_plan,
            resources=resources,
            blockers=blockers,
            success_criteria=success_criteria,
            step_1=steps[0] if steps else "Assess situation",
            step_2=steps[1] if len(steps) > 1 else "Gather required information",
            step_3=steps[2] if len(steps) > 2 else "Take appropriate action",
            additional_steps=additional_steps,
            notes=notes
        )
        
        return plan_content
    
    def _generate_task_summary(self, content: str, frontmatter: dict) -> str:
        """Generate a brief task summary"""
        # Extract body content (after frontmatter)
        body_match = re.search(r'---\s*\n.*?\n---\s*\n(.*)', content, re.DOTALL)
        body = body_match.group(1) if body_match else content
        
        # Take first few lines as summary
        lines = body.strip().split('\n')
        summary_lines = []
        
        for line in lines[:5]:
            line = line.strip()
            if line and not line.startswith('#'):
                summary_lines.append(line)
            if len(summary_lines) >= 3:
                break
        
        summary = ' '.join(summary_lines)
        
        # Truncate if too long
        if len(summary) > 300:
            summary = summary[:297] + "..."
        
        return summary if summary else "Task requires analysis and action."
    
    def _format_context(self, context: dict) -> str:
        """Format context information for the plan"""
        context_parts = []
        
        # Company handbook rules
        if context.get('rules'):
            rules = context['rules']
            if isinstance(rules, dict):
                if 'approval_thresholds' in rules:
                    context_parts.append(
                        f"- **Approval Thresholds**: Auto-approve under ${rules['approval_thresholds'].get('auto_approve_under', 50)}"
                    )
                if 'communication' in rules:
                    comm = rules['communication']
                    context_parts.append(
                        f"- **Communication**: Response time {comm.get('response_time_hours', 2)}h, Tone: {comm.get('tone', 'professional')}"
                    )
        
        # Sender history
        sender_history = context.get('sender_history', [])
        if sender_history:
            context_parts.append(
                f"- **Sender History**: {len(sender_history)} previous interactions found"
            )
        
        # Similar past tasks
        similar_tasks = context.get('recent_similar_tasks', [])
        if similar_tasks:
            context_parts.append(
                f"- **Similar Tasks**: {len(similar_tasks)} similar tasks processed previously"
            )
        
        # Recent decisions
        recent = context.get('recent_decisions', [])
        if recent:
            context_parts.append(
                f"- **Recent Activity**: {len(recent)} decisions in current session"
            )
        
        if not context_parts:
            return "No specific context available. Follow Company Handbook guidelines."
        
        return '\n'.join(context_parts)
    
    def _generate_action_plan(
        self, 
        task_type: str, 
        frontmatter: dict,
        context: dict
    ) -> str:
        """Generate action plan based on task type"""
        plans = {
            'email': """1. **Read and Analyze**: Review email content and sender information
2. **Check Handbook**: Verify response guidelines and approval requirements
3. **Determine Priority**: Assess urgency based on content and keywords
4. **Draft Response**: Prepare appropriate response following guidelines
5. **Review and Send**: Verify response accuracy and send or request approval""",
            
            'payment': """1. **Validate Request**: Verify payment details and recipient
2. **Check Threshold**: Determine if approval is required based on amount
3. **Verify Vendor**: Check if recipient is a known vendor
4. **Check for Duplicates**: Ensure this payment hasn't been processed
5. **Execute or Request Approval**: Process payment or create approval request""",
            
            'invoice': """1. **Extract Details**: Identify client, service, and amount
2. **Lookup Client**: Retrieve client information and rates
3. **Calculate Amount**: Compute total based on services and rates
4. **Generate Invoice**: Create professional invoice document
5. **Send for Approval**: Submit invoice for review before sending""",
            
            'file_drop': """1. **Analyze File**: Determine file type and content
2. **Categorize**: Classify file into appropriate category
3. **Extract Action Items**: Identify any required actions from content
4. **Route File**: Move to appropriate folder based on category
5. **Create Action or Complete**: Create action item or mark as complete""",
            
            'linkedin': """1. **Review Topic**: Understand the post topic and goals
2. **Generate Content**: Create engaging post content
3. **Check Guidelines**: Verify content meets platform guidelines
4. **Add Hashtags**: Include relevant hashtags for visibility
5. **Schedule or Post**: Schedule for optimal time or request approval""",
        }
        
        return plans.get(task_type, """1. **Assess Situation**: Understand the task requirements
2. **Gather Information**: Collect all relevant context and data
3. **Check Guidelines**: Review Company Handbook for applicable rules
4. **Plan Actions**: Break down into specific, actionable steps
5. **Execute**: Take appropriate action or request approval""")
    
    def _identify_resources(self, task_type: str, frontmatter: dict) -> str:
        """Identify required resources for the task"""
        resources = []
        
        if task_type == 'email':
            resources.append("- Email client access")
            resources.append("- Company Handbook for response guidelines")
            if frontmatter.get('priority') == 'high':
                resources.append("- Quick decision-making capability")
        
        elif task_type == 'payment':
            resources.append("- Payment system access")
            resources.append("- Vendor database")
            resources.append("- Approval workflow access")
            amount = frontmatter.get('amount', 0)
            if amount > 200:
                resources.append("- Human approval required")
        
        elif task_type == 'invoice':
            resources.append("- Client database access")
            resources.append("- Invoice template")
            resources.append("- Rate sheet")
        
        elif task_type in ['linkedin', 'social_post']:
            resources.append("- Social media platform access")
            resources.append("- Content guidelines")
            resources.append("- Hashtag research tool")
        
        if not resources:
            return "- Standard AI Employee capabilities"
        
        return '\n'.join(resources)
    
    def _identify_blockers(
        self, 
        task_type: str, 
        frontmatter: dict,
        context: dict
    ) -> str:
        """Identify potential blockers"""
        blockers = []
        
        # Check for approval requirements
        if task_type == 'payment':
            amount = float(frontmatter.get('amount', 0))
            if amount > 50:
                blockers.append(f"- Payment over $50 requires human approval")
            if amount > 200:
                blockers.append(f"- Large payment (${amount}) may have delayed approval")
        
        # Check for unknown sender
        if frontmatter.get('from') and not context.get('sender_history'):
            blockers.append("- Unknown sender may require additional verification")
        
        # Check for missing information
        if task_type == 'email' and not frontmatter.get('subject'):
            blockers.append("- Missing subject line may indicate incomplete data")
        
        # Check priority-based blockers
        if frontmatter.get('priority') == 'critical':
            blockers.append("- Critical priority - escalate immediately if blocked")
        
        if not blockers:
            return "No anticipated blockers"
        
        return '\n'.join(blockers)
    
    def _define_success_criteria(self, task_type: str, frontmatter: dict) -> str:
        """Define success criteria for the task"""
        criteria = {
            'email': """- Response sent within required timeframe
- Response follows Company Handbook guidelines
- Sender's issue or request addressed
- Email archived appropriately""",
            
            'payment': """- Payment validated and verified
- Appropriate approval obtained
- Payment executed successfully
- Transaction logged and documented""",
            
            'invoice': """- Invoice details accurate
- Client information correct
- Invoice approved and sent
- Record created in accounting system""",
            
            'file_drop': """- File content analyzed
- Appropriate category assigned
- File routed to correct location
- Action items identified and tracked""",
            
            'linkedin': """- Content generated and reviewed
- Guidelines compliance verified
- Post scheduled or published
- Activity logged""",
        }
        
        return criteria.get(task_type, """- Task analyzed and understood
- Appropriate action determined
- Action executed or approval requested
- Outcome documented""")
    
    def _generate_action_steps(
        self, 
        task_type: str, 
        frontmatter: dict
    ) -> List[str]:
        """Generate specific action steps"""
        steps_map = {
            'email': [
                "Read email content and identify key points",
                "Check Company Handbook for response guidelines",
                "Determine response priority and timeline",
                "Draft response following guidelines",
                "Review draft for accuracy and tone",
                "Send response or create approval request"
            ],
            'payment': [
                "Extract payment details (amount, recipient, reason)",
                "Validate payment information",
                "Check approval threshold requirements",
                "Look up vendor in database",
                "Check for duplicate payments",
                "Execute payment or create approval request"
            ],
            'invoice': [
                "Identify client and service details",
                "Look up client information and rates",
                "Calculate invoice amount",
                "Generate invoice document",
                "Review invoice for accuracy",
                "Submit for approval or send"
            ],
            'file_drop': [
                "Read file metadata and content",
                "Analyze file type and structure",
                "Categorize file content",
                "Extract any action items",
                "Route file to appropriate folder",
                "Create action file or mark complete"
            ],
            'linkedin': [
                "Review post topic and requirements",
                "Generate engaging content",
                "Check content against guidelines",
                "Add relevant hashtags",
                "Determine optimal posting time",
                "Create approval request or schedule"
            ]
        }
        
        return steps_map.get(task_type, [
            "Assess the situation and gather context",
            "Identify required actions",
            "Check applicable rules and guidelines",
            "Execute action or request approval",
            "Document the outcome"
        ])
    
    def _generate_notes(self, task_type: str, context: dict) -> str:
        """Generate additional notes"""
        notes = []
        
        # Add memory-based notes
        if context.get('recent_similar_tasks'):
            notes.append("- Similar tasks have been processed successfully in the past")
        
        if context.get('rules', {}).get('approval_thresholds'):
            notes.append("- Remember to follow approval threshold guidelines from Company Handbook")
        
        # Add type-specific notes
        if task_type == 'email':
            notes.append("- Maintain professional tone in all communications")
            notes.append("- Response time should align with priority level")
        
        elif task_type == 'payment':
            notes.append("- Always verify recipient before processing payment")
            notes.append("- Keep detailed records for audit purposes")
        
        if not notes:
            return "Follow Company Handbook guidelines and use best judgment."
        
        return '\n'.join(notes)
    
    def _generate_plan_filename(
        self, 
        task_file: Path, 
        frontmatter: dict
    ) -> str:
        """Generate a unique filename for the plan"""
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        task_type = frontmatter.get('type', 'task')
        
        # Create sanitized task identifier
        task_id = task_file.stem
        if len(task_id) > 30:
            task_id = task_id[:30]
        
        return f"PLAN_{task_type}_{task_id}_{timestamp}.md"
    
    def _parse_frontmatter(self, content: str) -> dict:
        """Parse YAML frontmatter from markdown content"""
        frontmatter = {}
        
        match = re.match(r'^---\s*\n(.*?)\n---\s*\n', content, re.DOTALL)
        
        if match:
            yaml_content = match.group(1)
            
            for line in yaml_content.split('\n'):
                if ':' in line:
                    key, value = line.split(':', 1)
                    key = key.strip()
                    value = value.strip()
                    
                    # Remove quotes
                    if (value.startswith('"') and value.endswith('"')) or \
                       (value.startswith("'") and value.endswith("'")):
                        value = value[1:-1]
                    
                    # Type conversion
                    if value.lower() == 'true':
                        value = True
                    elif value.lower() == 'false':
                        value = False
                    else:
                        try:
                            value = float(value)
                            if value == int(value):
                                value = int(value)
                        except ValueError:
                            pass
                    
                    frontmatter[key] = value
        
        return frontmatter
    
    def _get_memory_context(
        self, 
        frontmatter: dict, 
        task_content: str
    ) -> dict:
        """Get relevant context from memory store"""
        task_type = frontmatter.get('type', 'unknown')
        sender = frontmatter.get('from')
        
        return self.memory_store.get_context_for_task(
            task_type=task_type,
            sender=sender
        )
    
    def get_plan_template(self) -> str:
        """Get the plan template for reference"""
        return PLAN_TEMPLATE
